/*
 * @Author: OCEAN.GZY
 * @Date: 2024-01-19 16:12:01
 * @LastEditors: OCEAN.GZY
 * @LastEditTime: 2024-01-20 18:41:31
 * @FilePath: /vdesktop/include/CPU.h
 * @Description: 注释信息
 */
#pragma once

#include "MainBus.h"

class CPU
{
public:
    enum InterruptType // 中断类型
    {
        IRQ, /* Maskable interrupts (aka IRQs) can be generated by external circuitry on the cart  */
        NMI, /* NES uses non-maskable interrupts (NMIs) generated by PPU in the end of each frame (so-called VBlank interrupts).  */
        BRK_ /* Break */
    };

    // CPU连接总线
    CPU(MainBus &mem);

    void Reset();
    void Reset(Address start_addr);
    void SkipDMACycles();
    void Step();
    Address GetPC();
    void Interrupt(InterruptType t);

private:
    Address ReadAddress(Address addr);

    // 模拟指令执行
    bool ExecuteImplied(Byte opcode);
    bool ExecuteBranch(Byte opcode);
    bool ExecuteType0(Byte opcode);
    bool ExecuteType1(Byte opcode);
    bool ExecuteType2(Byte opcode);

    void SetPageCrossed(Address a, Address b, int inc = 1);

    // CPU exec instruction
    void PushStack(Byte value);
    Byte PullStack();
    void SetZN(Byte value);

    int m_skip_cycles;
    int m_cylces;

    // Registers 参考rockwell_r650x.pdf文件
    Address r_PC; // PC
    Byte r_SP;    // Stack Pointer
    Byte r_A;     // Accumulator
    Byte r_X;     // index Reg X
    Byte r_Y;     // index Reg Y

    // Processor Status Reg 处理器状态
    bool f_C; // Carry
    bool f_Z; // Zero
    bool f_I; // IRQ disable
    bool f_B; // Brk command
    bool f_D; // Decimal mode
    bool f_V; // Overflow
    bool f_N; // Negative

    MainBus &m_bus;
};
